### ISSUE TITLE
CI keeps failing

### ISSUE THREAD

**Issue by jfmengels** [jfmengels/node-elm-review#118]
THe CI keeps failing, even though the tests pass locally. This reduces my trust in the CI, and may at some point cause me to ship a version with broken code...

**Comment by hingew** [comment]
I just ran into the same issue. I tested the tests locally with multiple different node versions:

| Version | Result |
| ------- | ------ | 
| 14.17.6 | :x: |
| 16.20.2 | :x: |
| 18.20.3 | :x: |
| 20.14.0 | :heavy_check_mark: |
| 22.3.0  | :x: |

I guess the snapshots for the tests where recorded with the node version `20.x` but in the CI we use the version `16.x`. The node version `16.x` and `20.x` gives diffrent outputs for `JSON.parse(...)` errors.

A possible solution for this would be to enforce a node version for devleopment. This could be archived with one of the following options

-  [asdf](https://github.com/asdf-vm/asdf) and a `.tool-versions` file 
-  [nvm](https://github.com/nvm-sh/nvm) and a `.nvmrc`

**Comment by jfmengels** [comment]
Fixed by #157
