### ISSUE TITLE
Replace fs-extra

### ISSUE THREAD

**Issue by jfmengels** [jfmengels/node-elm-review#120]
In https://github.com/jfmengels/node-elm-review/pull/119 we replaced most usages of `fs-extra`.
We kept it because of the copy capabilities that it has that are not in `fs` or `graceful-fs`.

(Note: it's fine to keep it in `new-package/maintenance/update-examples-from-preview.js`, that's a separate generated project for packages)

**Comment by lydell** [comment]
According to https://nodejs.org/api/fs.html#fscopyfilesyncsrc-dest-mode, `fs.copyFileSync` has existed since Node.js 8.5.0, so after a quick search it looks like all that needs to be done is to change `fsExtra.copyFileSync` into `fs.copyFileSync` and then remove fs-extra.

**Comment by lishaduck** [comment]
Yay, cpSync is stable as of 22.3 (https://nodejs.org/en/blog/release/v22.3.0)
