### ISSUE TITLE
Add types to JS files

### ISSUE THREAD

**Issue by jfmengels** [jfmengels/node-elm-review#125]
I have added TypeScript to the project to help out with finding bugs during development.

Unfortunately, because without type annotations it determines that the arguments of pretty much every function is `any`, it doesn't report many problems in practice.

The idea is to add more types, so that there are none of these implicits `any`.

I have added TypeScript configuration that enables that setting for a few files, and have added all the necessary annotations for them, but I'm still missing a lot of the files. You can run it using

```
npx tsc --project tsconfig.no-implicit-any.json --watch
```

The idea is to update the `tsconfig.no-implicit-any.json` by adding a new file in the `include` list one and adding types until there are no more issues, and repeating until all files are done and we can enable the `noImplicitAny` setting in the regular `tsconfig.json` file.
I recommend adding new files that only import files that are already in the `include` list. (To do that, just add an arbitrary file, and if TS reports issues for other files, then choose one of those files instead, and so on).

Note that adding type annotations and fixing issues can result in the "main" tsconfig.json starting to report new issues.

If you'd like to work on this, great! And thank you!
Feel free to do as much or as little as you wish, I recommend to do small steps in this work, and to do for instance one PR per file added.

**Comment by lishaduck** [comment]
For the sake of future reference: #165, #166, #177, #179, #180, #181, #182, & #183.

**Comment by lishaduck** [comment]
Status: 27/51 production JS files (53%)

**Comment by lishaduck** [comment]
Making progress in #301! 

Status: 40/53 files

**Comment by lishaduck** [comment]
48/53!

**Comment by lishaduck** [comment]
> I highly appreciate the work and excitement, but go write your essay! 😅
> (as much as I understand why you prefer doing something else)

I know, I know. I'm gonna go finish it now 🙃
I do like writing, and I like the topic, this is just a lot more fun...

Well, off to write another couple hundred words...

**Comment by lishaduck** [comment]
Oh, can you close #132 as superseded, @jfmengels?
