### ISSUE TITLE
elm-review hangs in new project

### ISSUE THREAD

**Issue by wise-tim** [jfmengels/node-elm-review#137]
Follow up from https://elmlang.slack.com/archives/C010RT4D1PT/p1692789314256189

I ran elm-review in my Lamdera app on apple-silicon and it hangs with no output

Here is the output from elm-review --debug:

`elm-review --debug
Starting review application build
-- CONFIGURATION COMPILATION ERROR ---------------------------------------------

I encountered a problem when solving dependencies:

elm-json exited with signal SIGKILL

(empty stderr)
Error: I encountered a problem when solving dependencies:

elm-json exited with signal SIGKILL

(empty stderr)
    at /opt/homebrew/lib/node_modules/elm-review/lib/template-dependencies.js:50:13
    at /opt/homebrew/lib/node_modules/elm-review/lib/template-dependencies.js:291:29
    at async Object.getOrCompute (/opt/homebrew/lib/node_modules/elm-review/lib/cache.js:13:18)
    at async Promise.all (index 0)
    at async createTemplateProject (/opt/homebrew/lib/node_modules/elm-review/lib/build.js:315:43)
    at async Promise.all (index 1)
    at async buildLocalProject (/opt/homebrew/lib/node_modules/elm-review/lib/build.js:160:25)
    at async runElmReview (/opt/homebrew/lib/node_modules/elm-review/lib/main.js:50:51)`

Thanks for you help!

**Comment by jfmengels** [comment]
Thank you for the issue!
Can you tell me which version of Mac OS you're running? Is it an older version maybe? I know that on Monterey and older there are some issues running elm-json.

Also, can you tell me what the version of elm-json is? If you installzd elm-review locally, then elm-json should be in your node_modules (either directly or under elm-review I believe).

**Comment by timtimtam** [comment]
Apologies for the delay:

I am running Ventura 13.3 on an M1
I couldn't find elm-json anywhere in node-modules, but when I `npm i elm-json` I get version `0.2.13`

Running `npx elm-json tree` also hangs... which lead me to find this elm-json issue https://github.com/zwilias/elm-json/issues/54 that looks like it could describe my problem too. I think this, and the linked (but now expired) slack thread I what I recalled seeing earlier.

There is an open pull request that may fix it
https://github.com/zwilias/elm-json/pull/55/files

I might try and build elm-json from source to see if it works for me.

**Comment by timtimtam** [comment]
Please feel free to close this issue if you think it is appropriate.

**Comment by jfmengels** [comment]
Fixed by #144 :+1:

**Comment by timwisefmg** [comment]
Thankyou! Time to do some reviewing!

**Comment by jfmengels** [comment]
You should be able to try it out using the latest beta `npm install elm-review@beta`. Please open an issue if you notice a problem 😊
