### ISSUE TITLE
Internal parser application should use the same elm-syntax version as review applications

### ISSUE THREAD

**Issue by jhrcek** [jfmengels/node-elm-review#14]
To prevent issues like https://github.com/truqu/elm-review-noleftpizza/issues/3#issuecomment-649053318
we need to build the internal parser that elm-review CLI uses at build time of the review application, instead of at the build time of elm-review CLI tool.

**Comment by jfmengels** [comment]
Fixed in [`v2.4.1-beta.1`](https://github.com/jfmengels/node-elm-review/releases/tag/v2.4.1-beta.1), needed because we just releases v7.2.0 of elm-syntax, and we were still parsing using v7.1.3.
