### ISSUE TITLE
Unexpected error when loading an elm-review rule as a template

### ISSUE THREAD

**Issue by jxxcarlson** [jfmengels/node-elm-review#152]
When I run `npx elm-review --template jxxcarlson/elm-review-codeinstaller/example` I get the error below.  You can reproduce this by running the `npx` command in any elm project.  But don't use `--fix` or `--fix-all`: the rule can modify your code.

➜  counter npx elm-review --template jxxcarlson/elm-review-codeinstaller/example
✖ Downloading configuration files
-- UNEXPECTED ERROR ------------------------------------------------------------

I ran into an unexpected error. Please open an issue at the following link:
  https://github.com/jfmengels/node-elm-review/issues/new

Please include this error message and as much detail as you can provide. If you
can, please provide a setup that makes it easy to reproduce the error. That will
make it much easier to fix the issue.

Below is the error that was encountered.
--------------------------------------------------------------------------------
HTTPError: Response code 404 (Not Found)
    at Request.<anonymous> (/Users/carlson/node_modules/got/dist/source/as-promise/index.js:118:42)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

➜  counter ls /Users/carlson/node_modules/got/dist/source/as-promise/index.js
/Users/carlson/node_modules/got/dist/source/as-promise/index.js

**Comment by jfmengels** [comment]
Hi @jxxcarlson
I don't know if we solved the issue on Slack, but I can't reproduce the issue anymore. Please let me know if you run into a problem again.
