### ISSUE TITLE
TypeError: constraint.split is not a function

### ISSUE THREAD

**Issue by jamesrweb** [jfmengels/node-elm-review#154]
When running a fresh `elm-review` setup using the **_package_** template, the following error is thrown from the CLI:

<img width="1327" alt="Screenshot 2024-06-12 at 18 30 14" src="https://github.com/jfmengels/node-elm-review/assets/47126579/8c4d48a2-bbfa-4019-b030-f16076f3ac7a">

**Comment by jfmengels** [comment]
Hi @jamesrweb :wave: 

I'm not able to reproduce this by using the following:

```bash
cd some-elm-package/
elm-review init --template jfmengels/elm-review-config/package
elm-review
```

Could you provide a bit more information? The `elm.json` of your project seems relevant in this case.

**Comment by jamesrweb** [comment]
Yeah, [as mentioned in the slack](https://elmlang.slack.com/archives/C010RT4D1PT/p1718290284602809?thread_ts=1718210022.971409&cid=C010RT4D1PT), I don't know what happened since it resolved itself without me changing anything the next day. Closing for now and will re-open if it happens again.
