### ISSUE TITLE
`elm-json` is not found when ran with `npx`

### ISSUE THREAD

**Issue by jfmengels** [jfmengels/node-elm-review#2]
We use `elm-json` when building the configuration to compute the dependencies of the built app.

We currently spawn them using `npx` (see [here](https://github.com/jfmengels/node-elm-review/blob/master/lib/dependencies.js#L9)) but without the `--no-install` flag, which I think is the cause for a large startup time lag. From what I understand, running `npx` without this flag makes it try to download and install `elm-json` before running it if is not installed.

When trying to add the flag, the process crashes with the error "not found: elm-json". To me, this means that elm-json is not installed along with elm-review, and therefore npx tries to download it.

Making sure elm-json is probably installed along with elm-review will speed up the startup time.

**Comment by jfmengels** [comment]
I have re-added `--no-install` with v2.1.0, and it doesn't seem to be a problem anymore :man_shrugging:

**Comment by stil4m** [comment]
I've just encountered the following that seems to relate with this:

```
$ npm install -g elm-review
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
/Users/matstijl/.nvm/versions/node/v12.16.1/bin/elm-review -> /Users/matstijl/.nvm/versions/node/v12.16.1/lib/node_modules/elm-review/bin/elm-review

> elm-json@0.2.7 install /Users/matstijl/.nvm/versions/node/v12.16.1/lib/node_modules/elm-review/node_modules/elm-json
> binwrap-install

+ elm-review@2.2.0
added 168 packages from 160 contributors in 18.851s
MacBook-Pro-van-Mats:elm-avt matstijl$  git:(upstream ⚡ master) 5M 3A elm-review 
-- INCORRECT CONFIGURATION -----------------------------------------------------

I could not find a review configuration. I was expecting to find an elm.json file and a ReviewConfig.elm file in /Users/matstijl/development/repositories/bitbucket/stil4m/elm-avt/review/.

I can help set you up with an initial configuration if you run elm-review init.

$  elm-review init
✔ Would you like me to create elm.json and src/ReviewConfig.elm inside /Users/matstijl/development/repositories/bitbucket/stil4m/elm-avt/review? … yes

-- UNEXPECTED ERROR ------------------------------------------------------------

I ran into an unexpected error. Please open an issue at the following link:
  https://github.com/jfmengels/node-elm-review/issues/new

Please include this error message and as much detail as you can provide. If you
can, please provide a setup that makes it easy to reproduce the error. That will
make it much easier to fix the issue.

Below is the error that was encountered.
--------------------------------------------------------------------------------
Error: not found: elm-json

    at Socket.<anonymous> (/Users/matstijl/.nvm/versions/node/v12.16.1/lib/node_modules/elm-review/lib/spawn-async.js:11:21)
    at Socket.emit (events.js:311:20)
    at addChunk (_stream_readable.js:294:12)
    at readableAddChunk (_stream_readable.js:275:11)
    at Socket.Readable.push (_stream_readable.js:209:10)
    at Pipe.onStreamRead (internal/stream_base_commons.js:186:23)
```

Is `elm-json` a prerequisite when running `elm-review`?

**Comment by jfmengels** [comment]
Yes, but it should be installed along with it, since it is a dependency. I must not understand something essential about node_modules and binaries here...

**Comment by jfmengels** [comment]
Oh, it's because you installed it globally and apparently that does not add `elm-json` to the `$PATH` (which sounds very reasonable actually).

I don't know whether I should remove `--no-install` (making the CLI quite slower) or if I should print an error saying how to install `elm-json` :thinking: 
Thoughts anybody?

**Comment by jfmengels** [comment]
This is not an issue anymore, we now call `elm-json` directly through the path provided when we require it.
