### ISSUE TITLE
Unused modules not removed

### ISSUE THREAD

**Issue by Birowsky** [jfmengels/node-elm-review#45]
Upon running `elm-review --template jfmengels/elm-review-unused/example --fix-all` I get notified that there are a few unused modules and that I should remove them. Am I wrong to expect that those modules should be removed by this tool?

**Comment by jfmengels** [comment]
Hey @Birowsky :wave:

You're not necessarily wrong, but `elm-review` capabilities with regards to automatic fixes are too limited for this. Fixes are limited to **editing** files (Elm files, `elm.json` or `README.md`).

So you're not wrong, but `elm-review` won't do this kind of fixes, so you'll have to do it on your own. Maybe we'll support more kinds of fixes in the future, but that would require more research. In this case, I'd be worried of creating a file, doing work in it, running elm-review and too easily removing the file before I could add it to Git and keep a version of my changes.

When you edit a file, at least the editor would keep the file open so you could also undo the action, but when a file gets deleted, the editor often closes the tab so there's no way to get your latest changes.

This is the kind of reasons why I don't think I'll implement this anytime soon, especially considering the low amount of effort it takes to remove unused modules.

(I'll close the issue but if you have input, please leave a comment!)
