### ISSUE TITLE
Error: elm-json exited with signal SIGABRT

### ISSUE THREAD

**Issue by 8n8** [jfmengels/node-elm-review#51]
When using elm-review in the Nix package manager, I ran into this message, so am posting it here as requested:

(Sorry if I'm doing this wrong. I've never posted a Github issue before.)

```
-- UNEXPECTED ERROR ------------------------------------------------------------

I ran into an unexpected error. Please open an issue at the following link:
  https://github.com/jfmengels/node-elm-review/issues/new

Please include this error message and as much detail as you can provide. If you
can, please provide a setup that makes it easy to reproduce the error. That will
make it much easier to fix the issue.

Below is the error that was encountered.
--------------------------------------------------------------------------------
Error: elm-json exited with signal SIGABRT
    at ChildProcess.<anonymous> (/nix/store/04f2xpjs4z3qnz0qn4i018vb0wzggjmw-node_elm-review-2.4.6/lib/node_modules/elm-review/lib/template-dependencies.js:223:27)
    at ChildProcess.emit (events.js:375:28)
    at maybeClose (internal/child_process.js:1055:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:288:5)
```
These steps reproduce the issue (I am using Ubuntu Linux, but it should work on any Linux / Mac, where Nix is available):
1. install Nix package manager using [these instructions](https://nixos.org/guides/install-nix.html)
2. make a new directory and ```cd``` into it
3. make a new file called shell.nix with these contents:
```
{ pkgs ? import (fetchTarball "https://github.com/NixOS/nixpkgs/archive/a165aeceda9f9741d15bc2488425daeb06c0707e.tar.gz") {} }:

pkgs.mkShell {
  buildInputs = [
    pkgs.elmPackages.elm-review
    pkgs.elmPackages.elm
  ];
}
```
4. run ```nix-shell --pure``` to go into an isolated shell
5. do ```elm init``` and agree to question
6. do ```elm-review init``` and agree to question

The issue only happens with the ```--pure``` option to nix-shell, so my theory is that elm-review is not properly packaged on Nix, and actually depends on something, probably elm-json from a quick look at the Javascript file mentioned in the error message.

**Comment by lydell** [comment]
Small update: elm-review might not need elm-json in the future, which might solve this issue: https://github.com/jfmengels/node-elm-review/issues/61#issuecomment-1023483505

**Comment by gpampara** [comment]
Indeed, this and #61 are fundamentally the same root issue.
