### ISSUE TITLE
Consider allowing node-elm-review to work in offline mode

### ISSUE THREAD

**Issue by gpampara** [jfmengels/node-elm-review#61]
Firstly `elm-review` is a fantastic tool! Allowing for custom rules to align with team decisions is very liberating :) So thank you again for this!

I'd like to propose that there be an `offline` or `disconnected` type of execution mode that is intended primarily for CI. Although this is not a concern generally, within our CI configuration (hydra and nix) we build our code in a sandbox that does not have access to the internet. In this scenario, `elm-review` fails to execute due to `elm-json` being unable to communicate with `packages.elm-lang.com`.

In this case, using the offline execution, it is possible to short-circuit the `elm-json solve` step with the current contents of `elm.json`. There are, of course, caveats with this as the environment would be **expected** to have all dependencies present and available for use. This is a hard requirement for a sandbox build so not a problem in this scenario.

I'd be curious about your thoughts on this. A crude patch that we have been applying to `elm-review` locally is [available here](https://github.com/circuithub/node-elm-review/commit/d167d4548c72b50d25cad995eeeaf8d541e2be94) (currently based off of `elm-review` 2.5.1).

**Comment by lydell** [comment]
What did you do about the Elm compiler making HTTP requests to fetch packages?

**Comment by gpampara** [comment]
@lydell Those are managed using [elm2nix](https://github.com/cachix/elm2nix) which ensures that the local `registry.dat` is present for the compiler. Essentially `ELM_HOME` is setup in this process.

**Comment by lydell** [comment]
In my testing with elm-json 0.2.10, it already fall backs to local data. I disconnected from the Internet and elm-json printed:

```
phase: retrieve
 Oct 07 19:02:20.617 WARN Failed to fetch versions from package.elm-lang.org
<regular output>
```

**Comment by lydell** [comment]
> Now that elm-tooling-cli is being used to resolve elm-json this becomes a little more problematic as the hash check would fail when the elm-json binary is replaced with a script/binary that just produces the desired resolution data.

Just re-read this. No, that wouldn’t be a problem. `elm-tooling` only does the hash check on _download,_ not for executables that already exist (by design).

**Comment by gpampara** [comment]
I'm experimenting with some alternative ideas - will update this issue if I find anything else that will work.

**Comment by lydell** [comment]
Small update – there’s a chance elm-review won’t need to download `elm-json` anymore, by using [elm-solve-deps-wasm](https://github.com/mpizenberg/elm-solve-deps-wasm) instead, which “basically is a WebAssembly port of the dependency solver inside elm-test-rs.” So just a regular npm package with no “download extra stuff from the Internet” shenanigans.

node-test-runner (elm-test) currently uses elm-tooling just like node-elm-review, and there’s PR going there to switch to the other approach: https://github.com/rtfeldman/node-test-runner/pull/558

If that works out I’m sure we’d be able to do the same thing in elm-review.
