### ISSUE TITLE
Unexpected end of JSON input

### ISSUE THREAD

**Issue by puruzio** [jfmengels/node-elm-review#7]
I get the above error when running `elm-review init` on Windows 10.
I'm on elm 0.19.1 and elm-review 2.0.0.

C:\myProject>elm-review init
√ Would you like me to create elm.json and src/ReviewConfig.elm inside C:\myProject\review? ... yes
C:\myProject\review\elm.json: Unexpected end of JSON input

**Comment by jfmengels** [comment]
Hey @puruzio :wave: 

Thanks for trying it out and reporting the issue!
Can you reproduce this consistently?

Could you try running `elm-review init --debug`? That should print out the stacktrace and give me a bit more information about where this is happening.

I'd say it's likely a network error, but even if I can't improve, I could at least give a nicer error message.

Also, I just released a v2.0.1 which fixes something in the `init` output that you might want to get before initializing your repo (but that shouldn't help with this issue).

**Comment by puruzio** [comment]
Yes I can reproduce it consistently. Interestingly `--debug` doesn't have the same issue. (See below)
```

C:\myProject>elm-review init --debug
√ Would you like me to create elm.json and src/ReviewConfig.elm inside C:\myProject\review? ... yes

All done! I have created a review project at C:\myProject\review/ for you.

You can now define your review configuration by editing C:\myProject\review\src\ReviewConfig.elm.

I recommend you take a look at the following documents:
  - How to configure elm-review: https://github.com/jfmengels/elm-review/#Configuration
  - When to write or enable a rule: https://github.com/jfmengels/elm-review/#when-to-write-or-enable-a-rule


C:\myProject>elm-review init
√ Would you like me to create elm.json and src/ReviewConfig.elm inside C:\myProject\review? ... yes
C:\myProject\review\elm.json: Unexpected end of JSON input
```

**Comment by jfmengels** [comment]
That is really weird, because there is no logic related to the debug flag being enabled/disabled for the `init` subcommand... :thinking: 

Could you share with me what the `elm.json` looks like? Both with `--debug` and without?

**Comment by puruzio** [comment]
elm.json was the same when I ran with --debug or without.
```

{
    "type": "application",
    "source-directories": [
        "src"
    ],
    "elm-version": "0.19.1",
    "dependencies": {
        "direct": {
            "elm/core": "1.0.5",
            "elm/json": "1.1.3",
            "elm/project-metadata-utils": "1.0.1",
            "jfmengels/elm-review": "2.0.0",
            "stil4m/elm-syntax": "7.1.1"
        },
        "indirect": {
            "elm/html": "1.0.0",
            "elm/parser": "1.1.0",
            "elm/random": "1.0.0",
            "elm/time": "1.0.0",
            "elm/url": "1.0.0",
            "elm/virtual-dom": "1.0.2",
            "elm-community/json-extra": "4.2.0",
            "elm-community/list-extra": "8.2.4",
            "elm-explorations/test": "1.2.2",
            "rtfeldman/elm-hex": "1.0.0",
            "rtfeldman/elm-iso8601-date-strings": "1.1.3",
            "stil4m/structured-writer": "1.0.2"
        }
    },
    "test-dependencies": {
        "direct": {
            "elm-explorations/test": "1.2.2"
        },
        "indirect": {}
    }
}
```

**Comment by jfmengels** [comment]
@puruzio could you try this again with v2.0.2? I made a change which *could* solve the problem, bit I'm not confident :crossed_fingers:

**Comment by hanachurch** [comment]
That did the trick. No more error messages. Thank you!

**Comment by puruzio** [comment]
That did the trick. No more error messages. Thank you!!

**Comment by jfmengels** [comment]
Great! Thanks for letting me know!
