### ISSUE TITLE
I ran into an unexpected error. Please open an issue at the following link:

### ISSUE THREAD

**Issue by bigos** [jfmengels/node-elm-review#85]
Error: elm-json exited with exit code 1
    at ChildProcess.<anonymous> (/home/jacekp/.config/yarn/global/node_modules/elm-review/lib/template-dependencies.js:221:27)
    at ChildProcess.emit (events.js:314:20)
    at maybeClose (internal/child_process.js:1022:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:287:5)

**Comment by jfmengels** [comment]
Hi @bigos

Could you provide more information about this issue? For instance:
- What command did you run to get this issue?
- Do you get this error consistently or only sometimes?
- What is your OS? (MacOS/WIndows/Linux/...)
- other things that you think might be useful to help me figure out the issue

**Comment by lydell** [comment]
@jfmengels It might also be good to show stdout and stderr from elm-json in the error message.

**Comment by bigos** [comment]
This is what I did
```

jacekp@EID6043:~/Programming/Elm/collections$ npx elm-review --template jfmengels/elm-review-unused/example --fix-all
✔ Fetching template information
jacekp@EID6043:~/Programming/Elm/collections$ git status
On branch master
Your branch is ahead of 'origin/master' by 1 commit.
  (use "git push" to publish your local commits)

nothing to commit, working tree clean
jacekp@EID6043:~/Programming/Elm/collections$ elm review
There is no review command.

Run `elm` with no arguments to get more hints.

jacekp@EID6043:~/Programming/Elm/collections$ elm-review
-- INCORRECT CONFIGURATION -----------------------------------------------------

I could not find a review configuration. I was expecting to find an elm.json file and a ReviewConfig.elm file in /home/jacekp/Programming/Elm/collections/review/.

I can help set you up with an initial configuration if you run elm-review init.

jacekp@EID6043:~/Programming/Elm/collections$ elm-review init
✔ Would you like me to create elm.json and src/ReviewConfig.elm inside /home/jacekp/Programming/Elm/collections/review? … yes
-- UNEXPECTED ERROR ------------------------------------------------------------

I ran into an unexpected error. Please open an issue at the following link:
  https://github.com/jfmengels/node-elm-review/issues/new

Please include this error message and as much detail as you can provide. If you
can, please provide a setup that makes it easy to reproduce the error. That will
make it much easier to fix the issue.

Below is the error that was encountered.
--------------------------------------------------------------------------------
Error: elm-json exited with exit code 1
    at ChildProcess.<anonymous> (/home/jacekp/.config/yarn/global/node_modules/elm-review/lib/template-dependencies.js:221:27)
    at ChildProcess.emit (events.js:314:20)
    at maybeClose (internal/child_process.js:1022:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:287:5)


```

**Comment by bigos** [comment]
```
$ cat /etc/*-release
DISTRIB_ID=LinuxMint
DISTRIB_RELEASE=21
DISTRIB_CODENAME=vanessa
DISTRIB_DESCRIPTION="Linux Mint 21 Vanessa"
NAME="Linux Mint"
VERSION="21 (Vanessa)"
ID=linuxmint
ID_LIKE="ubuntu debian"
PRETTY_NAME="Linux Mint 21"
VERSION_ID="21"
HOME_URL="https://www.linuxmint.com/"
SUPPORT_URL="https://forums.linuxmint.com/"
BUG_REPORT_URL="http://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/"
PRIVACY_POLICY_URL="https://www.linuxmint.com/"
VERSION_CODENAME=vanessa
UBUNTU_CODENAME=jammy
```

**Comment by bigos** [comment]
```
$ node --version
v12.22.9
```

**Comment by bigos** [comment]
This in node installed from apt. On previous installation, I had node installed in another way. Could some leftovers from the previous installation be a problem?
```
$ which node
/usr/bin/node

```

**Comment by bigos** [comment]
https://github.com/bigos/Pyrulis/blob/master/Elm/installin-npm.org 

I have started with a clean state and installed everything. Following suggestion on elm slack I have installed VSCode find installed relevant plugin https://github.com/elm-tooling/elm-language-client-vscode.

I have a working elm-review.

**Comment by jfmengels** [comment]
I'm happy that it's working for you. I'll close this issue since I'm lacking information to address it.

I have made changes on the master branch so that we hopefully get more information from the tool. That said, the errors that I could manually trigger seemed to already have some nice error messages. I'm not sure we'll get better messages in practice.

Doing https://github.com/jfmengels/node-elm-review/issues/81 would solve the pain-points we've had with `elm-json` though.
