### ISSUE TITLE
elm-review --fix 2.8.4 doesn't report any errors

### ISSUE THREAD

**Issue by sporto** [jfmengels/node-elm-review#91]
Using 2.8.3

![image](https://user-images.githubusercontent.com/1005498/206064309-d39429ee-6f66-4a42-a6a8-242826ef60b5.png)

![image](https://user-images.githubusercontent.com/1005498/206064321-997c3de4-6349-4e30-89e1-cdc56965dd89.png)

Then using 2.8.4

![image](https://user-images.githubusercontent.com/1005498/206064384-4e6250c6-404c-4942-a056-5669f29b2d3e.png)

![image](https://user-images.githubusercontent.com/1005498/206064350-1f338572-b94b-4515-925b-5967a15f10ec.png)

**Comment by jfmengels** [comment]
Oh that's bad. Thank you for reporting. I'll take a look when I can. I think it's probably related to the introduction of this line https://github.com/jfmengels/node-elm-review/blob/master/template/src/Elm/Review/Main.elm#L893 but unsure as to what the consequences of changing that will be.

**Comment by rupertlssmith** [comment]
I also had similar issues with --fix-all. It would report errors, but then running with --fix-all it would report no errors or a different number of errors, give the appearance that they were fixed, but the source code is not changed at all.

Going back to 2.8.3 and it works fine.
