### ISSUE TITLE
elm-review becomes very slow and crashes after upgrade to 2.9

### ISSUE THREAD

**Issue by harmboschloo** [jfmengels/node-elm-review#98]
First of all thanks for this great tool. It's very useful.

Unfortunately I encountered a problem. After upgrading to version 2.9.0/2.9.1 running `elm-review` becomes very slow. Going from 3.5s on 2.8.5 to 46.0s on 2.9.0/2.9.1 on one project.

On a different project it's also slow and crashes after some time with this error:

> <--- Last few GCs --->
> 
> [9560:000002C52C77DC60]    75253 ms: Scavenge (reduce) 4090.5 (4105.3) -> 4090.4 (4106.6) MB, 1.9 / 0.0 ms  (average mu = 0.421, current mu = 0.004) allocation failure
> [9560:000002C52C77DC60]    75420 ms: Mark-sweep (reduce) 4098.0 (4113.8) -> 4097.5 (4113.8) MB, 144.3 / 0.0 ms  (+ 63.5 ms in 35 steps since start of marking, biggest step 9.1 ms, walltime since start of marking 223 ms) (average mu = 0.402, current mu = 0
> 
> <--- JS stacktrace --->
> 
> FATAL ERROR: Reached heap limit Allocation failed - JavaScript heap out of memory

`elm-review` was taking 4GB of memory at the time of the crash.

I'm running on Windows 11 Home with Node v16.16.0 and have 32GB memory.

So I don't really have an idea what the problem could be. Is there a way I can debug this?

It does remind me of problems I had with `elm-language-client-vscode` and `elm-webpack-loader` where to many simultaneous `Promise`s are eating up the systems resources. This might be a Windows only problem. But I don't really know what the problem for `elm-review` is.

For reference: https://github.com/elm-community/elm-webpack-loader/issues/192 and https://github.com/elm-tooling/elm-language-client-vscode/issues/390#issuecomment-1266723543

Thanks.

**Comment by harmboschloo** [comment]
Our review config looks like this btw.

```
config : List Rule
config =
    [ NoDebug.Log.rule
    , NoDebug.TodoOrToString.rule
    , NoExposingEverything.rule
    , NoImportingEverything.rule []
    , NoMissingTypeAnnotation.rule
    , NoMissingTypeExpose.rule
    , NoUnused.Dependencies.rule
    , NoUnused.Variables.rule
    , NoUnused.CustomTypeConstructors.rule []
    ]
```

I also tried `npx elm-review --template jfmengels/elm-review-unused/example` and that seems to work fine. 🤔

**Comment by harmboschloo** [comment]
So it seems the problem is caused by `NoUnused.CustomTypeConstructors.rule`. The other rules run fine.

**Comment by harmboschloo** [comment]
Oh I found the problem. Is turned we where still using `jfmengels/review-unused` instead of `jfmengels/elm-review-unused`. All is good again.

Sorry for the noise 😅

**Comment by jfmengels** [comment]
No worries!
v2.9.0 introduced some performance improvements by saving the cache for the results of the analysis on the file-system (somewhere in `elm-stuff`). Unfortunately the results are worse than expected and introduce issues similar to the one you reported. I have therefore not dared announce them. I'm still hoping to find a magical solution but am also considering undoing the changes.

So please let me know if you run into this again :pray:
